service: serverless-authorizer

provider: 
 name: aws
 runtime: nodejs8.10

functions:
  profile:
    handler: index.profile
    events:
      - http:
          path: profile
          method: get
          authorizer: auth
  auth:
    handler: index.auth

